Repository berty/weshnet, pull requests merged in 2023-04, with the labels that each got.

#49 chore: disable goconst in lint
  .golangci.yml
Labels: 🔍 Ready for Review, ✅ Approved

#50 feat: new functions that allow the parsing of connectivity info
  pkg/netmanager/connectivity.go
Labels: 🔍 Ready for Review

#51 fix: bump orbitdb to 1.20.1
  go.mod
  go.sum
Labels: ✅ Approved

#45 fix: In processMessageLoop, process the message without a goroutine
  go.mod
  store_message.go
Labels: 🔍 Ready for Review

#56 feat: function to create noop netmanager
  pkg/netmanager/netmanager_noop.go
Labels: 🔍 Ready for Review

#23 fix: Only declare groupID once In setHeadsForGroup and OpenGroup
  orbitdb.go
Labels: ✅ Approved

#58 fix: In processMessageLoop, call muDeviceCaches.Unlock() before continue
  store_message.go
Labels: ✅ Approved

#60 chore: Remove unused CODEOWNERS
  .github/CODEOWNERS
Labels: ✅ Approved

#62 feat: Drop unavailable peer connection when network connectivity change
  pkg/ipfsutil/lifecycle.go
Labels: ✅ Approved

#63 chore: Add doc comment for NewPersistentServiceClient .
  service_client.go
Labels: 🔍 Ready for Review

#65 chore: In the GitHub bug template, remove the automatic assignee to QA
  .github/ISSUE_TEMPLATE/bug_template.yml
Labels: ✅ Approved
